export const GateAccessReasonCode = {
  ENTRY_BOOKING_CONFIRMED: 'ENTRY_BOOKING_CONFIRMED',
  ENTRY_ASSIGNMENT_AUTO_BOOKING: 'ENTRY_ASSIGNMENT_AUTO_BOOKING',
  ENTRY_ACTIVE_SESSION_RETURN: 'ENTRY_ACTIVE_SESSION_RETURN',
  EXIT_ACTIVE_SESSION: 'EXIT_ACTIVE_SESSION',
  MANUAL_OVERRIDE: 'MANUAL_OVERRIDE',

  GATE_INACTIVE: 'GATE_INACTIVE',
  AUTO_OPEN_DISABLED: 'AUTO_OPEN_DISABLED',
  DEVICE_DISABLED: 'DEVICE_DISABLED',
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  DEVICE_NOT_AUTHENTICATED: 'DEVICE_NOT_AUTHENTICATED',
  VEHICLE_NOT_FOUND: 'VEHICLE_NOT_FOUND',
  CREDENTIAL_NOT_FOUND: 'CREDENTIAL_NOT_FOUND',
  CREDENTIAL_REVOKED: 'CREDENTIAL_REVOKED',
  CREDENTIAL_EXPIRED: 'CREDENTIAL_EXPIRED',
  NO_ACTIVE_BOOKING: 'NO_ACTIVE_BOOKING',
  NO_ACTIVE_SESSION: 'NO_ACTIVE_SESSION',
  BOOKING_NOT_CONFIRMED: 'BOOKING_NOT_CONFIRMED',
  ALREADY_CHECKED_IN: 'ALREADY_CHECKED_IN',
  ANPR_LOW_CONFIDENCE: 'ANPR_LOW_CONFIDENCE',
  DUPLICATE_DETECTION: 'DUPLICATE_DETECTION',
  WRONG_GATE_DIRECTION: 'WRONG_GATE_DIRECTION',
  NO_BARRIER_CONTROLLER: 'NO_BARRIER_CONTROLLER',

  ANPR_MULTIPLE_MATCHES: 'ANPR_MULTIPLE_MATCHES',
  PLATE_PARTIAL_MATCH: 'PLATE_PARTIAL_MATCH',

  ORCHESTRATION_FAILED: 'ORCHESTRATION_FAILED',
  MANUAL_OVERRIDE_RATE_LIMITED: 'MANUAL_OVERRIDE_RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type GateAccessReasonCodeValue =
  (typeof GateAccessReasonCode)[keyof typeof GateAccessReasonCode];