spring.application.name=payment-service
server.port=${SERVER_PORT:8081}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/parking_payment_db?createDatabaseIfNotExist=false&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:parking_user}
spring.datasource.password=${DB_PASSWORD:kpk@@440}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized
